---
name: "Build"
"on":
  pull_request:
  push:
  schedule:
    # Weekly
    - cron: '0 15 * * FRI'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        # Currently some crypto-related test failures on
        # ‘nixpkgs-unstable’ or I’d test that too.
        nixpkgs:
          - "true"
          - "nxp=release-21.11"
          - "nxp=release-21.05;pch=ff9c0b459ddc4b79c06e19d44251daa8e9cd1746"
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v10
        with:
          name: league
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - run: |
          nxp=""
          pch=""
          eval "${{ matrix.nixpkgs }}"
          if [[ "$nxp" != "" ]]; then
            nix flake lock --override-input nixpkgs "nixpkgs/$nxp"
          fi
          if [[ "$pch" != "" ]]; then
            nix flake lock --override-input pre-commit-hooks \
              "github:cachix/pre-commit-hooks.nix/$pch"
          fi
      - run: nix flake metadata
      - run: nix flake check
      - run: nix build --print-build-logs .#notmuch.{out,man,info}
      - run: nix build --print-build-logs .#emacs-notmuch
