---
name: "Build"
"on":
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        nixpkgs: ["pinned", "release-21.11", "nixpkgs-unstable"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: |
          if [[ "${{ matrix.nixpkgs }}" == "pinned" ]]; then
              nix flake metadata
          else
              nix flake update --override-input nixpkgs \
                  "nixpkgs/${{ matrix.nixpkgs }}"
          fi
      - run: nix flake check
      - run: nix build --print-build-logs .#notmuch.{out,emacs,man,info}
