---
name: "Build"
"on":
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
      - run: nix flake check
      - run: nix build .#notmuch.{out,emacs,man,info}
