---
name: "Update flake inputs"
on:
  workflow_dispatch:
  schedule:
    - cron: '20 1 15 * *'       # @monthly on 15th
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.4.0
      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v8
        with:
          pr-title: "Update flake inputs"
          token: ${{ secrets.GH_TOKEN_FOR_UPDATES }}
